services:
  db:
    image: postgres:15
    container_name: nest_postgres_db
    restart: always
    environment:
      POSTGRES_USER: dikshabj
      POSTGRES_PASSWORD: mypasswordisdiksha
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: